Components/CartSummaryViewComponent.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using BookStore.Models;

namespace BookStore.Components
{
    public class CartSummaryViewComponent : ViewComponent
    {
        private Cart cart;

        //constructor
        public CartSummaryViewComponent(Cart cartservice)
        {
            cart = cartservice;
        }

        public IViewComponentResult Invoke()
        {
            return View(cart);
        }
    }
}

Components/NavigationMenuViewComponent.cs
using BookStore.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BookStore.Components
{
    public class NavigationMenuViewComponent : ViewComponent
    {
        private IBookStoreRepository repository;

        public NavigationMenuViewComponent(IBookStoreRepository repo)
        {
            repository = repo;
        }
        public IViewComponentResult Invoke()
        {
            ViewBag.CurrCategory = RouteData?.Values["category"];

            return View(repository.Books
                .Select(x => x.Category)
                .Distinct()
                .OrderBy(x => x));
        }
    }
}

Views/Shared/BookSummary.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
@model Book

<div class="card card-outline-primary p-4 bg-light mb-5" style="margin: 5px;">
    <h4>
        <span class="card-title float-left">@Model.Title</span>
        <span class="badge badge-light float-right text-secondary">
            @Model.AuthorFirstName @Model.AuthorMiddleName @Model.AuthorLastName
        </span>
    </h4>
    <div class="text-info">
        <p><strong>@Model.Publisher</strong></p>
        <p>@Model.ISBN</p>
        <p>@Model.Classificaton</p>
        <p>@Model.Category</p>
        <p>$@Model.Price</p>
        <p>@Model.Pages</p>
    </div>

    <form id="@Model.BookId" asp-page="/AddToCart" method="post">
        <input type="hidden" asp-for="BookId" />
        <input type="hidden" name="returnUrl" value="@ViewContext.HttpContext.Request.PathAndQuery()" />
        <span class="cart-text p-1">
            @Model.Title
            <button type="submit" class="btn-success btn-sm pull-right" style="float:right">
                Add to Cart
            </button>
        </span>
    </form>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>BookStore</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link href="~/lib/font-awesome/css/all.css" rel="stylesheet" />
</head>
<body>
    <nav class="navbar navbar-inverse" style="background-color: #232f3e;">
        <div class="container-fluid">
            <div class="navbar-header">
                <a style="color:white !important;" class="navbar-brand" asp-action="Index">
                Most-Deifinitly-Not-Amazon</a>
            </div>
            <div class="col-6 text-right">
                <vc:cart-summary />
            </div>
        </div>
    </nav>
    <div style="margin-top:100px;" class="container">
        <div class="row m-1 p-1">
            <div class="col-3">
                <h1>@ViewBag.Title</h1>
                <vc:navigation-menu />
            </div>
            <div class="col-9">
                @RenderBody()
            </div>
        </div>
          
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>