Pages/AddToCart.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using BookStore.Infrastructure;
using BookStore.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace BookStore.Pages
{
    public class CartModel : PageModel
    {
        private IBookStoreRepository repository;

        //constructor
        public CartModel (IBookStoreRepository repo, Cart cartService)
        {
            repository = repo;
            Cart = cartService;
        }

        //properties
        public Cart Cart { get; set; }
        public string ReturnUrl { get; set; }

        public void OnGet(string returnUrl)
        {
            ReturnUrl = returnUrl ?? "/";
            //delete
            //Cart = HttpContext.Session.GetJson<Cart>("cart") ?? new Cart();
        }

        //methods
        //handler for the button to add a book to cart
        public IActionResult OnPost(long bookId, string returnUrl)
        {
            Book book = repository.Books
                .FirstOrDefault(b => b.BookId == bookId);
            //delete
           // Cart = HttpContext.Session.GetJson<Cart>("cart") ?? new Cart();

            Cart.AddItem(book, 1);
            //delete
            //HttpContext.Session.SetJson("cart", Cart);

            return RedirectToPage(new { returnUrl = returnUrl });
        }

        //handler for the remove button
        public IActionResult OnPostRemove(long bookId, string returnUrl)
        {
            Cart.RemoveItem(Cart.Lines.First(cl =>
                cl.Book.BookId == bookId).Book);

            //HttpContext.Session.SetJson("cart", Cart);

            return RedirectToPage(new { returnUrl = returnUrl });
        }
    }
}

Pages/AddToCart.cshtml
@page
@model BookStore.Pages.CartModel
@{
}

<h2>Your Cart</h2>
<div class="container">
    <table class="table table-bordered table-striped">
        <thead>
            <tr>
                <th>Book</th>
                <th>Quantity</th>
                <th>Price</th>
                <th>Subtotal</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var line in Model.Cart.Lines)
            {
                <tr>
                    <td class="text-left">@line.Book.Title</td>
                    <td class="text-center">@line.Quantity</td>
                    <td class="text-right">@((line.Book.Price).ToString("c"))</td>
                    <td class="text-right">@((line.Quantity * line.Book.Price).ToString("c"))</td>
                    <td class="text-center">
                        <form asp-page-handler="Remove" method="post">
                            <input type="hidden" name="BookId" value="@line.Book.BookId" />
                            <input type="hidden" name="returnUrl" value="@Model.ReturnUrl" />
                            <button type="submit" class="btn btn-sm btn-danger">Remove</button>
                        </form>
                    </td>
                </tr>
            }
        </tbody>
        <tfoot>
            <tr>
                <td lass="text-right" colspan="3">Total:</td>
                <td class="text-right">@Model.Cart.ComputeTotalSum().ToString("c")</td>
            </tr>
        </tfoot>
    </table>
</div>
<div class="col-3 text-center">
    <a class="btn btn-primary" href="@Model.ReturnUrl">Continue Shopping</a>
</div>